version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules 