version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=New_password123
      - DB_NAME=gcp
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules 