name: Build and Deploy to GCP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: clear-veld-461918-s2
  SERVICE_ACCOUNT: check-233@clear-veld-461918-s2.iam.gserviceaccount.com
  REGION: us-central1
  ARTIFACT_REPOSITORY: check
  IMAGE_NAME: gcp-backend
  DB_HOST: 104.198.198.225
  DB_NAME: gcp
  DB_USER: root
  DB_PASSWORD: New_password123

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Debug environment variables
      run: |
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
        echo "SERVICE_ACCOUNT: ${{ env.SERVICE_ACCOUNT }}"
        echo "REGION: ${{ env.REGION }}"
        echo "ARTIFACT_REPOSITORY: ${{ env.ARTIFACT_REPOSITORY }}"
        echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
        echo "GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}"
        echo "DB_HOST: ${{ env.DB_HOST }}"
        echo "DB_NAME: ${{ env.DB_NAME }}"
        echo "DB_USER: ${{ env.DB_USER }}"
        echo "DB_PASSWORD: ${{ env.DB_PASSWORD }}"
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
    
    - name: Build and push Docker image
      run: |
        docker build -t '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}' \
          --build-arg DB_HOST='104.198.198.225' \
          --build-arg DB_NAME='gcp' \
          --build-arg DB_USER='root' \
          --build-arg DB_PASSWORD='New_password123' .
        docker push '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
